### ISSUE TITLE
cluster auto-scale in azure-china not available

### ISSUE THREAD

**Issue by shm007g** [Azure/container-service-for-azure-china#42]
- [here](https://github.com/Azure/container-service-for-azure-china/tree/master/aks) shows chinaeast2 support aks preview with top available k8s version 1.11.4.
- [here](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler) `Before you begin` part says cluster auto-scale needs at least k8s 1.12.4 and vmss.
- they conflict with each other.
- I tried to install 1.12.4 version k8s, failed with `Operation failed with status: 'Bad Request'. Details: The value of parameter orchestratorProfile.OrchestratorVersion is invalid.`
- I tried with `az extension add --name aks-preview`, also failed with status: `No registered resource provider found for location 'chinaeast2' and API version '2018-08-01-preview' for type 'managedClusters'. The supported api-versions are '2017-08-31, 2018-03-31'. The supported locations are 'chinaeast2'.`
- **So, How can I use aks preview in azure china with cluster auto-scale function? Even in preview?**

**Comment by karataliu** [comment]
Thanks for reporting this.

You can get latest version support table via command:
```
az aks get-versions -l chinaeast2 -o table 
```

For 'auto-scale', it relies on `VMSSPreview` feature, which is still a preview feature in `azure global`, see [doc](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler).
 `azure china` doesn't support preview features for now. You can try `azure global` if you would like to try preview features.

**Comment by shm007g** [comment]
@karataliu
Thanks for you reply.
So, cluster auto-scale not available in Azure China AKS Preview? Am I right?
If so, I may try acs-engine instead.

Thanks.

**Comment by shm007g** [comment]
> Thanks for reporting this.
> 
> You can get latest version support table via command:
> 
> ```
> az aks get-versions -l chinaeast2 -o table 
> ```
> For 'auto-scale', it relies on `VMSSPreview` feature, which is still a preview feature in `azure global`, see [doc](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler).
> `azure china` doesn't support preview features for now. You can try `azure global` if you would like to try preview features.

**Comment by shm007g** [comment]
> Thanks for reporting this.
> 
> You can get latest version support table via command:
> 
> ```
> az aks get-versions -l chinaeast2 -o table 
> ```
> For 'auto-scale', it relies on `VMSSPreview` feature, which is still a preview feature in `azure global`, see [doc](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler).
> `azure china` doesn't support preview features for now. You can try `azure global` if you would like to try preview features.

**Comment by karataliu** [comment]
Yes, that's correct.

Besides, `acs-engine` has renamed to [aks-engine](https://github.com/Azure/aks-engine), you can redirect to the new project.

Thanks for your consideration.

**Comment by shm007g** [comment]
@karataliu
Thanks.
I want to know if cluster autoscaler could be implemented with aks-engine/acs-engine?
Where should I start with?

Thanks.

**Comment by shm007g** [comment]
By the way, does AKS global support cluster autoscaler with vmss?
When will this feature ship to china?

**Comment by andyzhangx** [comment]
> I want to know if cluster autoscaler could be implemented with aks-engine/acs-engine?
Where should I start with?

@shm007g 
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/README.md#acs-deployment
And to use aks-engine on Azure China, you could start with https://github.com/Azure/container-service-for-azure-china/tree/master/aks-engine, use the `VM Scale Set cluster example` in the doc

**Comment by shm007g** [comment]
@andyzhangx @karataliu Thanks.

**Comment by shm007g** [comment]
> Thanks for reporting this.
> 
> You can get latest version support table via command:
> 
> ```
> az aks get-versions -l chinaeast2 -o table 
> ```
> For 'auto-scale', it relies on `VMSSPreview` feature, which is still a preview feature in `azure global`, see [doc](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler).
> `azure china` doesn't support preview features for now. You can try `azure global` if you would like to try preview features.


You said VMSSPreview is a preview feature even in azure global. But I created a cluster scalable k8s cluster with acs-engine(0.25.3) + k8s(1.12) based on VMSS in `Azure China`!

So, this VMSSPreview function should be ok in china to make my k8s CA working.

Am i wrong?

**Comment by shm007g** [comment]
And this [k8s markdown](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/azure/README.md#acs-deployment) says it's ok with vmss or standard vmtype for CA.

And your [doc](https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler) says only vmss support CA. Your MS docs conflict with K8S docs here.

**Comment by andyzhangx** [comment]
Hi @shm007g, `az aks update --update-cluster-autoscaler` command(autoscaler integrated with AKS) is only for AKS and only work with AKS VMSSPreview, it's easier to use;
while if you use aks-engine, autoscaler works with both vmss and standard vmtype, but you need to deploy autoscaler by yourself and configure a lot compared to `az aks update --update-cluster-autoscaler` command, is that clear?

**Comment by shm007g** [comment]
> Hi @shm007g, `az aks update --update-cluster-autoscaler` command(autoscaler integrated with AKS) is only for AKS and only work with AKS VMSSPreview, it's easier to use;
> while if you use aks-engine, autoscaler works with both vmss and standard vmtype, but you need to deploy autoscaler by yourself and configure a lot compared to `az aks update --update-cluster-autoscaler` command, is that clear?

I got what you said. 

I guess AKS build on aks-engine, AKS can support what aks-engine can support. According what you said, AKS now cut some function of aks-engine?

**Comment by andyzhangx** [comment]
correct, new features come into aks-engine first, and then AKS adopts those new features later

**Comment by shm007g** [comment]
> correct, new features come into aks-engine first, and then AKS adopts those new features later

Thanks.

So, for now cluster-autoscaler is only a preview function even in azure global. 
A formal cluster-autoscaler for azure china may take a real long time.
If we want to use this function in china, i can only use aks-engine/acs-engine instead.

If I get no mistake on upper conclusion, I may close this comment.

By the way, I've build one k8s cluster on acs-engine template with cluster-autoscaler function work well. But boss may want a formal version.

**Comment by andyzhangx** [comment]
correct, thanks for understanding. AKS will be GA on Azure China in the next few months, and then we will onboard cluster-autoscaler, that's the draft timeline.

**Comment by shm007g** [comment]
> correct, thanks for understanding. AKS will be GA on Azure China in the next few months, and then we will onboard cluster-autoscaler, that's the draft timeline.

I got you. Thanks.
