### ISSUE TITLE
AKS in azure-china can't run GPU workload. 

### ISSUE THREAD

**Issue by luna1230** [Azure/container-service-for-azure-china#44]
AKS in azure-china can't run GPU workload. because the “built-in Ubuntu image” **don't have nvidia-docker2** . Could we create a new image to support that ?  Thanks very much .

**Comment by andyzhangx** [comment]
It's in our road map, currently we don't support that, it's probably supported in GA time.

**Comment by andyzhangx** [comment]
@luna1230 it's now supported on Azure China AKS: https://github.com/Azure/container-service-for-azure-china/blob/master/aks/gpu-support.md
Let me know if you have any question.
