### ISSUE TITLE
Monitoring and logging are not available

### ISSUE THREAD

**Issue by blrchen** [Azure/container-service-for-azure-china#47]
I know this is listed in know issue page but am still opening an issue so people can track it via GitHub notification.

I am evaluating migrate aks from global Azure to Azure China, lacking of monitoring and logging will increase our DevOps effect. In addition, we need invest more resources on researching live site issue alerts solution, which sounds a duplicate effort for AKS China users.

**Comment by andyzhangx** [comment]
these functionality will be ready before GA, stay tuned.

**Comment by andyzhangx** [comment]
Monitoring and logging are enabled in Mooncake now
