### ISSUE TITLE
How to pull gcr.io images with sub-domain?

### ISSUE THREAD

**Issue by sirius1024** [Azure/container-service-for-azure-china#53]
e.g. k8s.gcr.io/addon-resizer:1.7

I've tried:
```sh
docker pull gcr.azk8s.cn/k8s.gcr.io/addon-resizer:1.7
docker pull gcr.azk8s.cn/gcr.io/addon-resizer:1.7
docker pull gcr.azk8s.cn/k8s/addon-resizer:1.7
docker pull gcr.azk8s.cn/addon-resizer:1.7
docker pull k8s.gcr.azk8s.cn/addon-resizer:1.7
```
doesn't work.

**Comment by andyzhangx** [comment]
`docker pull gcr.azk8s.cn/google_containers/addon-resizer:1.7`

Note: k8s.gcr.io would redirect to gcr.io/google-containers, following image urls are identical:
```
k8s.gcr.io/pause-amd64:3.1
gcr.io/google_containers/pause-amd64:3.1
```

**Comment by andyzhangx** [comment]
BTW, are you using this proxy on Azure cloud? @sirius1024

**Comment by sirius1024** [comment]
@andyzhangx Not yet. Only for my local development.
I thought Azure has its own proxy instead of mirror sites right?

**Comment by andyzhangx** [comment]
`*.azk8s.cn` is for container proxy on China.

**Comment by sirius1024** [comment]
Thanks for your response andy.
I close this issue now.
