### ISSUE TITLE
Container Registry Proxy limits

### ISSUE THREAD

**Issue by marcellbaan-viooh** [Azure/container-service-for-azure-china#56]
Hi there,

When we setup a bunch of new nodes we got error: 
`failed: rpc error: code = Unknown desc = failed pulling image "gcr.azk8s.cn/google_containers/pause-amd64:3.0": Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of>`
After when we changed our outgoing ip address we can use again the proxy.(we are using the proxy from AWS China)

There is any limit/throttling on *.azk8s.cn proxy?

**Comment by andyzhangx** [comment]
> Hi there,
> 
> When we setup a bunch of new nodes we got error:
> `failed: rpc error: code = Unknown desc = failed pulling image "gcr.azk8s.cn/google_containers/pause-amd64:3.0": Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of>`
> After when we changed our outgoing ip address we can use again the proxy.(we are using the proxy from AWS China)
> 
> There is any limit/throttling on *.azk8s.cn proxy?

Mainly it's for Microsoft, you could use that in outside for limited usage, while if you pull too many images in a short time, it will cause blocking from our side.

**Comment by marcellbaan-viooh** [comment]
Thank you very much for your reply!
