### ISSUE TITLE
It can't be used now

### ISSUE THREAD

**Issue by willzhang** [Azure/container-service-for-azure-china#58]
```
# docker pull gcr.azk8s.cn/google_containers/pause-amd64:3.2
Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
```

**Comment by andyzhangx** [comment]
From this moment, *.azk8s.cn is only allowed for Azure China IPs, sorry for the inconvenience.

**Comment by willzhang** [comment]
so sad!

**Comment by TimeBye** [comment]
Why suddenly stop providing services to the outside world? Does this document need to be modified?

https://github.com/Azure/container-service-for-azure-china/blob/master/aks/README.md

**Comment by andyzhangx** [comment]
The doc said:
we have set up container registry proxies on **Azure China** for public anonymous access

**Comment by iBug** [comment]
@andyzhangx That doesn't match what you might intend to mean. It could at all be interpreted as

> we have set up container registry proxies on Azure China (= that are hosted on Azure China) for public (anyone, anywhere) anonymous access

**Comment by uzxmx** [comment]
I also encountered this issue. Seems that Azure mirrors are only for private access in China (not public access in China). As a last resort, I use gcr images which are mirrored to dockerhub. For anyone who's interested in using official docker registry or a mirror like `docker.mirrors.ustc.edu.cn` to access gcr images, you can find useful information [here](https://github.com/uzxmx/dockerhub-build-trigger).

**Comment by andyzhangx** [comment]
> I also encountered this issue. Seems that Azure mirrors are only for private access in China (not public access in China). As a last resort, I use gcr images which are mirrored to dockerhub. For anyone who's interested in using official docker registry or a mirror like `docker.mirrors.ustc.edu.cn` to access gcr images, you can find useful information [here](https://github.com/uzxmx/dockerhub-build-trigger).

This `gcr.azk8s.cn` is mainly for Microsoft users, thanks for understanding.
