### ISSUE TITLE
Pulling From mcr.azk8s.cn Results in HTTP 403

### ISSUE THREAD

**Issue by taoyouh** [Azure/container-service-for-azure-china#60]
When trying to use the azk8s proxy, I run into HTTP 403 error.
I tried to pull the image described in the [doc](https://github.com/Azure/container-service-for-azure-china/blob/master/aks/README.md#22-container-registry-proxy):
```
docker pull mcr.azk8s.cn/oss/kubernetes/hyperkube:v1.15.7
```
The result it returned is:
```
Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
```

**Comment by andyzhangx** [comment]
sorry, 目前 *.azk8s.cn 已经仅限于 Azure China IP 使用，不再对外提供服务, 如果确实有需求，可以联系akscn@microsoft.com 并提供IP地址，我们会根据需求 做决定是否对特定IP提供服务，谢谢理解。

Sorry, currently *.azk8s.cn could only be accessed by Azure China IP, we don't provide public access any more. If you have such requirement to whitelist your IP, please contact akscn@microsoft.com, provide you IP address, we will decide whether to whitelist your IP per your reasonable requirement, thanks for understanding.
