### ISSUE TITLE
unable to pull images

### ISSUE THREAD

**Issue by Dragnell87** [Azure/container-service-for-azure-china#61]
Hi, hopping the team is safe under the codiv-19 pandemic, i would like to report that i am unable to pull any image from 

dockerhub.azk8s.cn
or 
gcr.azk8s.cn

for a while now, the error is:

Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"

Best regards.

**Comment by andyzhangx** [comment]
Sorry, currently *.azk8s.cn could only be accessed by Azure China IP, we don't provide public outside access any more. If you have such requirement to whitelist your IP, please contact akscn@microsoft.com, provide your IP address, we will decide whether to whitelist your IP per your reasonable requirement, thanks for understanding.
