### ISSUE TITLE
Container Registry Proxy  403 Forbidden

### ISSUE THREAD

**Issue by bombomla** [Azure/container-service-for-azure-china#62]
docker pull dockerhub.azk8s.cn/library/mysql:5.7
Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"

**Comment by andyzhangx** [comment]
https://mirror.azure.cn/help/en/docker-registry-proxy-cache.html
Proxy Server could only be accessed by Azure China IP, we don't provide public outside access any more. If you have such requirement to whitelist your IP, please contact akscn@microsoft.com, provide your IP address, we will decide whether to whitelist your IP per your reasonable requirement, thanks for understanding.

**Comment by blademainer** [comment]
👎

**Comment by blademainer** [comment]
> https://mirror.azure.cn/help/en/docker-registry-proxy-cache.html
> Proxy Server could only be accessed by Azure China IP, we don't provide public outside access any more. If you have such requirement to whitelist your IP, please contact [akscn@microsoft.com](mailto:akscn@microsoft.com), provide your IP address, we will decide whether to whitelist your IP per your reasonable requirement, thanks for understanding.

👎
