### ISSUE TITLE
The ‘dockerhub.azk8s.cn’ proxy has ‘403 Forbidden’ problem

### ISSUE THREAD

**Issue by scenerycm** [Azure/container-service-for-azure-china#63]
When i pull the dockerhub registry  with the proxy 'dockerhub.azk8s.cn', the response is ‘403 Forbidden’.
`Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
`

**Comment by andyzhangx** [comment]
Note: currently *.azk8s.cn could only be accessed by Azure China IP, we don't provide public outside access any more. If you have such requirement to whitelist your IP, please contact akscn@microsoft.com, provide your IP address, we will decide whether to whitelist your IP per your reasonable requirement, thanks for understanding. @
