### ISSUE TITLE
service down today. Will you continue?

### ISSUE THREAD

**Issue by Yensan** [Azure/container-service-for-azure-china#68]
Today, my docker can't pull images. I check everything, find
```sh
$ ping dockerhub.azk8s.cn
PING east2mirrorlb.chinaeast2.cloudapp.chinacloudapi.cn (40.73.69.67): 56 data bytes
Request timeout for icmp_seq 0
```

I delete ` "https://dockerhub.azk8s.cn"` from  `/etc/docker/daemon.json  >>  "registry-mirrors": []` list, then everything is OK.

What happened?  Is it just down  in accidental, OR, Microsoft Azure will always close `dockerhub.azk8s.cn` ？

I hope `dockerhub.azk8s.cn` run forever.  😄

**Comment by andyzhangx** [comment]
@Yensan btw, are you trying image pull on Azure VM? if your machine is not Azure VM, image pulling would be blocked.

**Comment by Yensan** [comment]
> 

oh，I just use my docker in linux, NOT an Azure VM ....
thank you for reply.
