### ISSUE TITLE
Container Registry Proxy for registry.k8s.io

### ISSUE THREAD

**Issue by jmajoor** [Azure/container-service-for-azure-china#71]
The documentation explains how to use the proxy reqistry k8sgcr.azk8s.cn for nginx in the China region.
However newer versions of the nginx Helm chart use the  registry.k8s.io registry. Is there a different proxy for this?

**Comment by jmajoor** [comment]
The documentation mentions that both 
k8s.gcr.io and registry.k8s.io are proxied by k8sgcr.azk8s.cn

I am experiencing problems with the latest Helm Nginx update.

The previous version 4.6.0 used: 
k8sgcr.azk8s.cn/ingress-nginx/kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794

The latest version 4.7.0 uses:
k8sgcr.azk8s.cn/ingress-nginx/kube-webhook-certgen:v20230407

Both version are defining registry.k8s.io in their default Helm values and I used k8sgcr.azk8s.cn successfully on the old 4.6.0 version.

However k8sgcr.azk8s.cn/ingress-nginx/kube-webhook-certgen:v20230407 fails with an "error: timed out waiting for the condition"

For testing I also used the following command:
kubectl run hello-world -ti --rm --image=k8sgcr.azk8s.cn/ingress-nginx/kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794 --restart=Never -- version

This works with the 4.6.0 version.

The command fails for the 4.7.0 version:
kubectl run hello-world -ti --rm --image=k8sgcr.azk8s.cn/ingress-nginx/kube-webhook-certgen:v20230407 --restart=Never -- version

Is there a different proxy that needs to be used?

**Comment by andyzhangx** [comment]
I think the problem is where is the source image? k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v20230407 does not exist

**Comment by jmajoor** [comment]
The source image is not in k8s.gcr.io, but in registry.k8s.io.
There is however not a separate proxy for registry.k8s.io and the documentation mentions that you can use the same proxy (k8sgcr.azk8s.cn) for it.

If I do my test from a US region then I get similar results using k8s.gcr.io.
My tests do work using  registry.k8s.io.

**Comment by jmajoor** [comment]
I experience more problems.
An image on docker.io (perfectly valid in US region) gives me a "i/o timeout" error in the K8S event log.
Using dockerhub.azk8s.cn instead will give me a "not found" error.

**Comment by andyzhangx** [comment]
> I experience more problems. An image on docker.io (perfectly valid in US region) gives me a "i/o timeout" error in the K8S event log. Using dockerhub.azk8s.cn instead will give me a "not found" error.

@jmajoor can you provide the full image address? btw, we are already setting up new registry server for registry.k8s.io

**Comment by andyzhangx** [comment]
> Turns out that image is in a private repository in docker hub. Is the proxy passing through credentials or are private repositories in docker hub simply not supported?
> 
> Thanks for setting up registry.k8s.io.

@jmajoor No, unless you give your password to me, just kidding.

**Comment by andyzhangx** [comment]
pls try registryk8s.azk8s.cn, it should work now:

```
# docker pull registryk8s.azk8s.cn/ingress-nginx/kube-webhook-certgen:v20230407
v20230407: Pulling from ingress-nginx/kube-webhook-certgen
10f855b03c8a: Pull complete
fe5ca62666f0: Pull complete
fff4e558ad3a: Pull complete
fcb6f6d2c998: Pull complete
e8c73c638ae9: Pull complete
1e3d9b7d1452: Pull complete
4aa0ea1413d3: Pull complete
7c881f9ab25e: Pull complete
5627a970d25e: Pull complete
baeaa1a3b0bf: Pull complete
Digest: sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b
Status: Downloaded newer image for registryk8s.azk8s.cn/ingress-nginx/kube-webhook-certgen:v20230407
```

**Comment by jmajoor** [comment]
Works like a charm. Got my nginx controller updated.
Thanks!
