### ISSUE TITLE
dockerhub proxy not woring

### ISSUE THREAD

**Issue by tw-zengyang** [Azure/container-service-for-azure-china#73]
I've recently noticed that some of the image resources are not available, is there a problem?

![image](https://github.com/user-attachments/assets/abf95f0f-07cf-4c76-a763-6248170df468)

docker pull dockerhub.azk8s.cn/library/openjdk:11-jdk-slim-bullseye

**Comment by bdfkockmeyer** [comment]
I also have this issue pulling images from here. 
![image](https://github.com/user-attachments/assets/3e757509-cc6d-4502-9081-f4df74125aab)

**Comment by superkartoffel** [comment]
I also see several images apparently missing from the proxy.  It seems to affect only certain versions and is also intermittent as some images used to be available some time ago.
For example:
dockerhub.azk8s.cn/bitnami/contour:1.29.2-debian-12-r0 ✅ works
dockerhub.azk8s.cn/bitnami/contour:1.30.0-debian-12-r6 ❎ not found
gcr.azk8s.cn/datadoghq/cluster-agent:7.56.2 ❎ today: not found
gcr.azk8s.cn/datadoghq/cluster-agent:7.56.2 ✅ 35days ago, worked
gcr.azk8s.cn/datadoghq/agent:7.56.2-jmx ❎ today: not found
gcr.azk8s.cn/datadoghq/agent:7.56.2-jmx ✅ 35days ago: worked

**Comment by andyzhangx** [comment]
Hi,
        The dockerhub in China is blocked by GFW, so that’s the main reason why you cannot pull those images. You could push those images to ACR and then use ACR on mooncake clusters, thanks.

**Comment by bdfkockmeyer** [comment]
Surry @andyzhangx but we are trying to pull the images from the mirror in china which is mentioned in this repository and not directly from dockerhub. But the images cannot be found in the china registry mirror. Can you tell me who is responsible for pushing the images to the miror?
